sonar.projectKey=JuanForero531_PetGo
sonar.projectName=PetGo
sonar.organization=juanforero531

sonar.sources=src
sonar.tests=src,__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=**/main.jsx,**/index.js,**/*.config.js,**/*.config.jsx
